import { useState } from "react";
import { Sidebar } from "../../components/Sidebar";
import { Header } from "../../components/Header";
import { Button } from "../../components/Button";
import { Settings, AlertCircle, ToggleLeft, CreditCard, Eye, EyeOff } from "lucide-react";

export default function AdminSettings() {
  const [platformName, setPlatformName] = useState("Vital FT Pics");
  const [disclaimer, setDisclaimer] = useState(
    "This platform provides informational predictions only. Predictions are generated by algorithms and do not guarantee outcomes. No guarantees are made regarding accuracy or results. Use at your own discretion."
  );
  const [paystackEnabled, setPaystackEnabled] = useState(true);
  const [paystackPublicKey, setPaystackPublicKey] = useState("pk_test_xxxxxxxxxxxxx");
  const [paystackSecretKey, setPaystackSecretKey] = useState("sk_test_xxxxxxxxxxxxx");
  const [showSecretKey, setShowSecretKey] = useState(false);
  const [features, setFeatures] = useState({
    predictionAnalysis: true,
    confidenceRatings: true,
    historicalData: true,
    userComments: false,
    emailNotifications: true,
  });

  const toggleFeature = (key: keyof typeof features) => {
    setFeatures({ ...features, [key]: !features[key] });
  };

  return (
    <div className="flex min-h-screen">
      <Sidebar isAdmin />
      <div className="flex-1 flex flex-col">
        <Header />
        <main className="flex-1 p-8">
          <div className="mb-8">
            <h2 className="text-2xl font-semibold mb-2">System Settings</h2>
            <p className="text-muted-foreground">Configure platform settings and features</p>
          </div>

          <div className="max-w-4xl space-y-6">
            {/* Platform Settings */}
            <div className="bg-card border border-border rounded-lg p-6">
              <div className="flex items-center gap-3 mb-6">
                <Settings className="text-primary" size={24} />
                <h3 className="text-xl font-semibold">Platform Configuration</h3>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="block text-sm mb-2">Platform Name</label>
                  <input
                    type="text"
                    value={platformName}
                    onChange={(e) => setPlatformName(e.target.value)}
                    className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                  <p className="text-sm text-muted-foreground mt-2">
                    This name appears across the entire platform
                  </p>
                </div>

                <div>
                  <label className="block text-sm mb-2">Platform Disclaimer</label>
                  <textarea
                    value={disclaimer}
                    onChange={(e) => setDisclaimer(e.target.value)}
                    rows={5}
                    className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary resize-none"
                  />
                  <p className="text-sm text-muted-foreground mt-2">
                    Legal disclaimer shown to all users
                  </p>
                </div>
              </div>

              <div className="mt-6">
                <Button>Save Platform Settings</Button>
              </div>
            </div>

            {/* Paystack Integration Section */}
            <div className="bg-card border border-border rounded-lg p-6">
              <div className="flex items-center gap-3 mb-6">
                <CreditCard className="text-primary" size={24} />
                <h3 className="text-xl font-semibold">Payment Integration (Paystack)</h3>
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Enable Paystack</div>
                    <div className="text-sm text-muted-foreground">
                      Toggle payment processing on/off
                    </div>
                  </div>
                  <button
                    onClick={() => setPaystackEnabled(!paystackEnabled)}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      paystackEnabled ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        paystackEnabled ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>

                <div>
                  <label className="block text-sm mb-2">Paystack Public Key</label>
                  <input
                    type="text"
                    value={paystackPublicKey}
                    onChange={(e) => setPaystackPublicKey(e.target.value)}
                    placeholder="pk_test_xxxxxxxxxxxxx"
                    className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                  <p className="text-sm text-muted-foreground mt-2">
                    Your Paystack public key (starts with pk_)
                  </p>
                </div>

                <div>
                  <label className="block text-sm mb-2">Paystack Secret Key</label>
                  <div className="relative">
                    <input
                      type={showSecretKey ? "text" : "password"}
                      value={paystackSecretKey}
                      onChange={(e) => setPaystackSecretKey(e.target.value)}
                      placeholder="sk_test_xxxxxxxxxxxxx"
                      className="w-full px-4 py-3 pr-12 bg-background border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
                    />
                    <button
                      type="button"
                      onClick={() => setShowSecretKey(!showSecretKey)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                    >
                      {showSecretKey ? <EyeOff size={20} /> : <Eye size={20} />}
                    </button>
                  </div>
                  <p className="text-sm text-muted-foreground mt-2">
                    Your Paystack secret key (starts with sk_) - Keep this private
                  </p>
                </div>

                <div className="bg-secondary/10 border border-secondary/20 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <AlertCircle size={20} className="text-secondary flex-shrink-0 mt-0.5" />
                    <div className="text-sm">
                      <p className="font-semibold mb-1">Security Notice</p>
                      <p className="text-muted-foreground">
                        Keys are securely stored and encrypted. Used for subscription payments and transaction processing. Never share your secret key publicly.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-6">
                <Button>Save Payment Settings</Button>
              </div>
            </div>

            {/* Feature Toggles */}
            <div className="bg-card border border-border rounded-lg p-6">
              <div className="flex items-center gap-3 mb-6">
                <ToggleLeft className="text-primary" size={24} />
                <h3 className="text-xl font-semibold">Feature Management</h3>
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Prediction Analysis</div>
                    <div className="text-sm text-muted-foreground">
                      Show detailed analysis for each prediction
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFeature("predictionAnalysis")}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      features.predictionAnalysis ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        features.predictionAnalysis ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Confidence Ratings</div>
                    <div className="text-sm text-muted-foreground">
                      Display confidence levels on predictions
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFeature("confidenceRatings")}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      features.confidenceRatings ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        features.confidenceRatings ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Historical Data</div>
                    <div className="text-sm text-muted-foreground">
                      Allow users to access past predictions
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFeature("historicalData")}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      features.historicalData ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        features.historicalData ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">User Comments</div>
                    <div className="text-sm text-muted-foreground">
                      Enable commenting on predictions
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFeature("userComments")}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      features.userComments ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        features.userComments ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-background/50 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Email Notifications</div>
                    <div className="text-sm text-muted-foreground">
                      Send email updates to users
                    </div>
                  </div>
                  <button
                    onClick={() => toggleFeature("emailNotifications")}
                    className={`w-14 h-8 rounded-full transition-colors relative ${
                      features.emailNotifications ? "bg-primary" : "bg-muted"
                    }`}
                  >
                    <div
                      className={`absolute top-1 w-6 h-6 bg-white rounded-full transition-transform ${
                        features.emailNotifications ? "translate-x-7" : "translate-x-1"
                      }`}
                    ></div>
                  </button>
                </div>
              </div>

              <div className="mt-6">
                <Button>Save Feature Settings</Button>
              </div>
            </div>

            {/* System Info */}
            <div className="bg-card border border-border rounded-lg p-6">
              <div className="flex items-center gap-3 mb-6">
                <AlertCircle className="text-primary" size={24} />
                <h3 className="text-xl font-semibold">System Information</h3>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div>
                  <div className="text-sm text-muted-foreground mb-1">Platform Version</div>
                  <div className="font-semibold">v1.0.0</div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground mb-1">Database Status</div>
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="font-semibold text-primary">Connected</span>
                  </div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground mb-1">API Status</div>
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="font-semibold text-primary">Operational</span>
                  </div>
                </div>
                <div>
                  <div className="text-sm text-muted-foreground mb-1">Last Backup</div>
                  <div className="font-semibold">March 22, 2026 02:00 AM</div>
                </div>
              </div>
            </div>

            {/* Danger Zone */}
            <div className="bg-card border border-destructive/30 rounded-lg p-6">
              <h3 className="text-xl font-semibold mb-4 text-destructive">Danger Zone</h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-destructive/10 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Clear All Predictions</div>
                    <div className="text-sm text-muted-foreground">
                      Remove all prediction data from the system
                    </div>
                  </div>
                  <Button variant="outline" className="border-destructive text-destructive hover:bg-destructive hover:text-white">
                    Clear Data
                  </Button>
                </div>
                <div className="flex items-center justify-between p-4 bg-destructive/10 rounded-lg">
                  <div>
                    <div className="font-semibold mb-1">Reset Algorithm</div>
                    <div className="text-sm text-muted-foreground">
                      Reset all algorithm weights to default values
                    </div>
                  </div>
                  <Button variant="outline" className="border-destructive text-destructive hover:bg-destructive hover:text-white">
                    Reset
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}